server.port: ${PORT:8080}
spring.datasource.url: ${DATABASE_URL}
spring.datasource.username: ${LOCAL_DB_USER}
spring.datasource.password: ${LOCAL_DB_PASS}
awskey: ${AWS_ACCESS_KEY_ID}
awssecret: ${AWS_SECRET_ACCESS_KEY}
